### ISSUE TITLE
Easing prevents serialization of Animation

### ISSUE THREAD

**Issue by mdgriffith** [mdgriffith/ui-animation#1]
Supporting easing functions in the model makes serialization difficult.  This isn't that big of a deal for UI, but it is potentially a big deal when saving state for a game.

One potential way forward is by providing easing functions by string name.  Not necessarily by having the user provide the exact name, but by providing the names as values that resolve to strings.

`quadraticEasing = "quadraticEasing"`

A custom easing option would then be provided which would not be serializable.

**Comment by mgold** [comment]
In mgold/elm-animation, I keep a function in a record but I agree it has some downsides. I means equality breaks, so I provide my own `equals` function that samples the easing function (there were a few other things I wanted to override too).

So having a fixed number of easing functions would be a totally viable way of doing this. I think you should consider using a large union type, like `type EasingRef = Linear | Quadratic | Sinusoidal` but those don't serialize without a bit of hand-holding.

BTW you know about elm-community/easing-functions right?

**Comment by mdgriffith** [comment]
Absolutely, elm-community/easing-functions is fantastic. 

Sampling the easing function for equality is really interesting. I was originally thinking of doing it with a union type like you mention, but with sampling I think there's a very cool option.  

We encode the easing as a sample list and to decode we require the user to provide a list of all the different easings they use in the project, and we match them via sampling.

**Comment by mgold** [comment]
Oh no, what have I done...

The relevant code from my lib is `List.all (\t -> a.ease t == b.ease t) [ 0.1, 0.3, 0.7, 0.9 ]`, where `a` and `b` are records containing an `ease : Float -> Float` field.

**Comment by mdgriffith** [comment]
Lol

I was thinking about it and there's another block to json serialization in this library for an animation and that is due to being able handle external `Msg`s.  We wouldn't be able to recreate those.

And most likely for saving state in a game you'd want to serialize on a higher level than the animation directly.

Also the sampling method would be brittle for any tiny adjustments to an easing :/  Like you save some json, change your easing function by a super tiny amount, and then your saved json doesn't want to load.

So for now I'm going to skip the serialization business altogether until/unless someone comes to me with a serious usecase :)

**Comment by mgold** [comment]
Use-case driven development. That's how we roll in Elm.

**Comment by mdgriffith** [comment]
word
